
### 图片验证码获取
GET http://127.0.0.1:8888/iku/sys/verifyCode/captcha


### 邮箱验证码获取
GET http://127.0.0.1:8888/iku/sys/verifyCode/captcha

### 用户注册
POST http://127.0.0.1:8888/iku/user/register
Accept: */*
Cache-Control: no-cache
Content-Type: application/json; charset=UTF-8


{
  "alimamaInfo": {
    "alimamaAdzone": "mm_366500004_403950091_108514000187",
    "adzoneName": "code",
    "appkey": "26036880",
    "secret": "287f267328af30369cb11c6227c3c129",
    "taobaoUserName": "爱酷科技网",
    "taobaoUserId": 366500004
  },
  "email": "healerjean@gmail.com",
  "password": "Iku..123",
  "realName": "iku",
  "telephone": "17610397651",
  "userId": 366500004,
  "userName": "ikuisme",
  "verifyCode": "a7gh",
   "mailCode": "jx2cf5"

}

### 用户登录
POST http://127.0.0.1:8888/iku/user/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json; charset=UTF-8

{

  "email": "healerjean@gmail.com",
  "password": "Iku..123",
  "verifyCode": "qq3u"
}



### 当前用户信息查询
GET http://127.0.0.1:8888/iku/user/current

###

