
// Copyright 2012 Google Inc. All rights reserved.
(function(){

var data = {
"resource": {
  "version":"7",
  "macros":[{
      "function":"__e"
    },{
      "function":"__u",
      "vtp_component":"URL",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__u",
      "vtp_component":"HOST",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__u",
      "vtp_component":"PATH",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__f",
      "vtp_component":"URL"
    },{
      "function":"__e"
    }],
  "tags":[{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/javascript\"\u003E-1==window.location.href.indexOf(\"braze.com\")\u0026\u0026+function(b,d,f,e,a){(a=b.createElement(d)).type=\"text\/javascript\";a.src=\"https:\/\/firebasestorage.googleapis.com\/v0\/b\/liner-firebase.appspot.com\/o\/liner_appboy.min.js?alt\\x3dmedia\\x26token\\x3d4b24ebe1-5771-4510-a7d3-bbb9e0783c35\";(c=b.getElementsByTagName(d)[0]).parentNode.insertBefore(a,c);a.addEventListener?a.addEventListener(\"load\",e,!1):a.readyState\u0026\u0026(a.onreadystatechange=e)}(document,\"script\",\"link\",function(){lnrAppboy.initialize(\"8f0d3f99-1e3f-4444-bb6c-f73da32cc97c\",\n{baseUrl:\"https:\/\/customer.iad-03.braze.com\/api\/v3\"});lnrAppboy.display.automaticallyShowNewInAppMessages();try{if(void 0!=linerVar)if(null!=linerVar.userInfo\u0026\u0026void 0!=linerVar.userInfo.id)lnrAppboy.changeUser(linerVar.userInfo.id);else return;else checkUserInfo()}catch(b){console.log(b)}lnrAppboy.openSession();window.lnrAppboy=lnrAppboy});\u003C\/script\u003E",
      "vtp_supportDocumentWrite":true,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "vtp_usePostscribe":true,
      "tag_id":1
    },{
      "function":"__html",
      "once_per_load":true,
      "vtp_html":"\u003Cscript src=\"\/\/eaap.getliner.com\/js\/ad.min.js\" charset=\"utf-8\"\u003E\u003C\/script\u003E\n",
      "vtp_supportDocumentWrite":true,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "vtp_usePostscribe":true,
      "tag_id":2
    }],
  "predicates":[{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.dom"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.js"
    }],
  "rules":[
    [["if",0],["add",0]],
    [["if",1],["add",1]]]
},
"runtime":[
[],[]
]


};
var aa,ca=this,da=/^[\w+/_-]+[=]{0,2}$/,ea=null,ka=function(a,b){function c(){}c.prototype=b.prototype;a.Wg=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Fg=function(a,c,g){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var la=function(){},ma=function(a){return"function"==typeof a},f=function(a){return"string"==typeof a},na=function(a){return"number"==typeof a&&!isNaN(a)},oa=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},qa=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},ra=function(a,b){if(a&&oa(a))for(var c=0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},sa=function(a,b){if(!na(a)||
!na(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},ta=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])},ua=function(a){return Math.round(Number(a))||0},va=function(a){return"false"==String(a).toLowerCase()?!1:!!a},wa=function(a){var b=[];if(oa(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},ya=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},za=function(){return(new Date).getTime()},Aa=function(){this.prefix="gtm.";this.values=
{}};Aa.prototype.set=function(a,b){this.values[this.prefix+a]=b};Aa.prototype.get=function(a){return this.values[this.prefix+a]};Aa.prototype.contains=function(a){return void 0!==this.get(a)};
var Ba=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Ca=function(a){var b=!1;return function(){if(!b)try{a()}catch(c){}b=!0}},Da=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},Ea=function(a){for(var b in a)if(a.hasOwnProperty(b))return!0;return!1},Fa=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Ga=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Ha=function(a){if(null==a)return String(a);var b=Ga.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Ia=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Ka=function(a){if(!a||"object"!=Ha(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Ia(a,"constructor")&&!Ia(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Ia(a,b)},p=function(a,b){var c=b||("array"==Ha(a)?[]:{}),d;for(d in a)if(Ia(a,d)){var e=a[d];"array"==Ha(e)?("array"!=Ha(c[d])&&(c[d]=[]),c[d]=p(e,c[d])):Ka(e)?(Ka(c[d])||(c[d]={}),c[d]=p(e,c[d])):c[d]=e}return c};var u=window,x=document,La=navigator,Ma=x.currentScript&&x.currentScript.src,Na=function(a,b){var c=u[a];u[a]=void 0===c?b:c;return u[a]},Oa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},Pa=function(a,b,c){var d=x.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;Oa(d,b);c&&(d.onerror=c);var e;if(null===ea)b:{var g=ca.document,h=g.querySelector&&g.querySelector("script[nonce]");
if(h){var k=h.nonce||h.getAttribute("nonce");if(k&&da.test(k)){ea=k;break b}}ea=""}e=ea;e&&d.setAttribute("nonce",e);var l=x.getElementsByTagName("script")[0]||x.body||x.head;l.parentNode.insertBefore(d,l);return d},Qa=function(){if(Ma){var a=Ma.toLowerCase();if(0===a.indexOf("https://"))return 2;if(0===a.indexOf("http://"))return 3}return 1},Ra=function(a,b){var c=x.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";var d=x.body&&x.body.lastChild||
x.body||x.head;d.parentNode.insertBefore(c,d);Oa(c,b);void 0!==a&&(c.src=a);return c},Sa=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a;return d},y=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},Ta=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},z=function(a){u.setTimeout(a,0)},Va=function(a){var b=
x.getElementById(a);if(b&&Ua(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(Ua(document.all[a][c],"id")==a)return document.all[a][c];return b},Ua=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Wa=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},Xa=function(a){var b=x.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=
[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},Ya=function(a,b,c){c=c||100;for(var d={},e=0;e<b.length;e++)d[b[e]]=!0;for(var g=a,h=0;g&&h<=c;h++){if(d[String(g.tagName).toLowerCase()])return g;g=g.parentElement}return null};var Za=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;var $a=/:[0-9]+$/,ab=function(a,b,c){for(var d=a.split("&"),e=0;e<d.length;e++){var g=d[e].split("=");if(decodeURIComponent(g[0]).replace(/\+/g," ")===b){var h=g.slice(1).join("=");return c?h:decodeURIComponent(h).replace(/\+/g," ")}}},C=function(a,b,c,d,e){b&&(b=String(b).toLowerCase());if("protocol"===b||"port"===b)a.protocol=bb(a.protocol)||bb(u.location.protocol);"port"===b?a.port=String(Number(a.hostname?a.port:u.location.port)||("http"==a.protocol?80:"https"==a.protocol?443:"")):"host"===b&&
(a.hostname=(a.hostname||u.location.hostname).replace($a,"").toLowerCase());var g=b,h,k=bb(a.protocol);g&&(g=String(g).toLowerCase());switch(g){case "url_no_fragment":h=cb(a);break;case "protocol":h=k;break;case "host":h=a.hostname.replace($a,"").toLowerCase();if(c){var l=/^www\d*\./.exec(h);l&&l[0]&&(h=h.substr(l[0].length))}break;case "port":h=String(Number(a.port)||("http"==k?80:"https"==k?443:""));break;case "path":h="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var m=h.split("/");0<=
qa(d||[],m[m.length-1])&&(m[m.length-1]="");h=m.join("/");break;case "query":h=a.search.replace("?","");e&&(h=ab(h,e,void 0));break;case "extension":var n=a.pathname.split(".");h=1<n.length?n[n.length-1]:"";h=h.split("/")[0];break;case "fragment":h=a.hash.replace("#","");break;default:h=a&&a.href}return h},bb=function(a){return a?a.replace(":","").toLowerCase():""},cb=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");b=0>c?a.href:a.href.substr(0,c)}return b},db=function(a){var b=x.createElement("a");
a&&(b.href=a);var c=b.pathname;"/"!==c[0]&&(c="/"+c);var d=b.hostname.replace($a,"");return{href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port}};var eb=function(a,b,c){for(var d=[],e=String(b||document.cookie).split(";"),g=0;g<e.length;g++){var h=e[g].split("="),k=h[0].replace(/^\s*|\s*$/g,"");if(k&&k==a){var l=h.slice(1).join("=").replace(/^\s*|\s*$/g,"");l&&c&&(l=decodeURIComponent(l));d.push(l)}}return d},hb=function(a,b,c,d){var e=fb(a,d);if(1===e.length)return e[0].id;if(0!==e.length){e=gb(e,function(a){return a.xb},b);if(1===e.length)return e[0].id;e=gb(e,function(a){return a.Ua},c);return e[0]?e[0].id:void 0}};
function ib(a,b,c){var d=document.cookie;document.cookie=a;var e=document.cookie;return d!=e||void 0!=c&&0<=eb(b,e).indexOf(c)}
var mb=function(a,b,c,d,e,g){d=d||"auto";var h={path:c||"/"};e&&(h.expires=e);"none"!==d&&(h.domain=d);var k;a:{var l=b,m;if(void 0==l)m=a+"=deleted; expires="+(new Date(0)).toUTCString();else{g&&(l=encodeURIComponent(l));var n=l;n&&1200<n.length&&(n=n.substring(0,1200));l=n;m=a+"="+l}var q=void 0,r=void 0,t;for(t in h)if(h.hasOwnProperty(t)){var v=h[t];if(null!=v)switch(t){case "secure":v&&(m+="; secure");break;case "domain":q=v;break;default:"path"==t&&(r=v),"expires"==t&&v instanceof Date&&(v=
v.toUTCString()),m+="; "+t+"="+v}}if("auto"===q){for(var w=kb(),A=0;A<w.length;++A){var E="none"!=w[A]?w[A]:void 0;if(!lb(E,r)&&ib(m+(E?"; domain="+E:""),a,l)){k=!0;break a}}k=!1}else q&&"none"!=q&&(m+="; domain="+q),k=!lb(q,r)&&ib(m,a,l)}return k};function gb(a,b,c){for(var d=[],e=[],g,h=0;h<a.length;h++){var k=a[h],l=b(k);l===c?d.push(k):void 0===g||l<g?(e=[k],g=l):l===g&&e.push(k)}return 0<d.length?d:e}
function fb(a,b){for(var c=[],d=eb(a),e=0;e<d.length;e++){var g=d[e].split("."),h=g.shift();if(!b||-1!==b.indexOf(h)){var k=g.shift();k&&(k=k.split("-"),c.push({id:g.join("."),xb:1*k[0]||1,Ua:1*k[1]||1}))}}return c}
var nb=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,ob=/(^|\.)doubleclick\.net$/i,lb=function(a,b){return ob.test(document.location.hostname)||"/"===b&&nb.test(a)},kb=function(){var a=[],b=document.location.hostname.split(".");if(4===b.length){var c=b[b.length-1];if(parseInt(c,10).toString()===c)return["none"]}for(var d=b.length-2;0<=d;d--)a.push(b.slice(d).join("."));a.push("none");return a};var Lb=[],Mb=[],Nb=[],Ob=[],Pb=[],Qb={},Rb,Sb,Tb,Ub=function(a,b){var c={};c["function"]="__"+a;for(var d in b)b.hasOwnProperty(d)&&(c["vtp_"+d]=b[d]);return c},Vb=function(a,b){var c=a["function"];if(!c)throw Error("Error: No function name given for function call.");var d=!!Qb[c],e={},g;for(g in a)a.hasOwnProperty(g)&&0===g.indexOf("vtp_")&&(e[d?g:g.substr(4)]=a[g]);return d?Qb[c](e):(void 0)(c,e,b)},Xb=function(a,b,c,d){c=c||[];d=d||la;var e={},g;for(g in a)a.hasOwnProperty(g)&&(e[g]=Wb(a[g],b,
c,d));return e},Yb=function(a){var b=a["function"];if(!b)throw"Error: No function name given for function call.";var c=Qb[b];return c?c.b||0:0},Wb=function(a,b,c,d){if(oa(a)){var e;switch(a[0]){case "function_id":return a[1];case "list":e=[];for(var g=1;g<a.length;g++)e.push(Wb(a[g],b,c,d));return e;case "macro":var h=a[1];if(c[h])return;var k=Lb[h];if(!k||b(k))return;c[h]=!0;try{var l=Xb(k,b,c,d);e=Vb(l,d);Tb&&(e=Tb.ff(e,l))}catch(E){d(E,h),e=!1}c[h]=!1;return e;case "map":e={};for(var m=1;m<a.length;m+=
2)e[Wb(a[m],b,c,d)]=Wb(a[m+1],b,c,d);return e;case "template":e=[];for(var n=!1,q=1;q<a.length;q++){var r=Wb(a[q],b,c,d);Sb&&(n=n||r===Sb.nb);e.push(r)}return Sb&&n?Sb.kf(e):e.join("");case "escape":e=Wb(a[1],b,c,d);if(Sb&&oa(a[1])&&"macro"===a[1][0]&&Sb.Nf(a))return Sb.Yf(e);e=String(e);for(var t=2;t<a.length;t++)pb[a[t]]&&(e=pb[a[t]](e));return e;case "tag":var v=a[1];if(!Ob[v])throw Error("Unable to resolve tag reference "+v+".");return e={wd:a[2],index:v};case "zb":var w={arg0:a[2],arg1:a[3],
ignore_case:a[5]};w["function"]=a[1];var A=Zb(w,b,c,d);a[4]&&(A=!A);return A;default:throw Error("Attempting to expand unknown Value type: "+a[0]+".");}}return a},Zb=function(a,b,c,d){try{return Rb(Xb(a,b,c,d))}catch(e){JSON.stringify(a)}return null};var $b=null,cc=function(a,b){function c(a){for(var b=0;b<a.length;b++)e[a[b]]=!0}var d=[],e=[];$b=ac(a,b||function(){});for(var g=0;g<Mb.length;g++){var h=Mb[g],k=bc(h);if(k){for(var l=h.add||[],m=0;m<l.length;m++)d[l[m]]=!0;c(h.block||[])}else null===k&&c(h.block||[])}for(var n=[],q=0;q<Ob.length;q++)d[q]&&!e[q]&&(n[q]=!0);return n},bc=function(a){for(var b=a["if"]||[],c=0;c<b.length;c++){var d=$b(b[c]);if(!d)return null===d?null:!1}for(var e=a.unless||[],g=0;g<e.length;g++){var h=$b(e[g]);if(null===
h)return null;if(h)return!1}return!0},ac=function(a,b){var c=[];return function(d){void 0===c[d]&&(c[d]=Zb(Nb[d],a,void 0,b));return c[d]}};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var dc,ec=function(){};(function(){function a(a,h){a=a||"";h=h||{};for(var k in b)b.hasOwnProperty(k)&&(h.Se&&(h["fix_"+k]=!0),h.xd=h.xd||h["fix_"+k]);var l={comment:/^\x3c!--/,endTag:/^<\//,atomicTag:/^<\s*(script|style|noscript|iframe|textarea)[\s\/>]/i,startTag:/^</,chars:/^[^<]/},q={comment:function(){var b=a.indexOf("--\x3e");if(0<=b)return{content:a.substr(4,b),length:b+3}},endTag:function(){var b=a.match(d);if(b)return{tagName:b[1],length:b[0].length}},atomicTag:function(){var b=q.startTag();
if(b){var c=a.slice(b.length);if(c.match(new RegExp("</\\s*"+b.tagName+"\\s*>","i"))){var d=c.match(new RegExp("([\\s\\S]*?)</\\s*"+b.tagName+"\\s*>","i"));if(d)return{tagName:b.tagName,C:b.C,content:d[1],length:d[0].length+b.length}}}},startTag:function(){var b=a.match(c);if(b){var d={};b[2].replace(e,function(a,b,c,e,h){var k=c||e||h||g.test(b)&&b||null,l=document.createElement("div");l.innerHTML=k;d[b]=l.textContent||l.innerText||k});return{tagName:b[1],C:d,Za:!!b[3],length:b[0].length}}},chars:function(){var b=
a.indexOf("<");return{length:0<=b?b:a.length}}},r=function(){for(var b in l)if(l[b].test(a)){var c=q[b]();return c?(c.type=c.type||b,c.text=a.substr(0,c.length),a=a.slice(c.length),c):null}};h.xd&&function(){var b=/^(AREA|BASE|BASEFONT|BR|COL|FRAME|HR|IMG|INPUT|ISINDEX|LINK|META|PARAM|EMBED)$/i,c=/^(COLGROUP|DD|DT|LI|OPTIONS|P|TD|TFOOT|TH|THEAD|TR)$/i,d=[];d.Jd=function(){return this[this.length-1]};d.xc=function(a){var b=this.Jd();return b&&b.tagName&&b.tagName.toUpperCase()===a.toUpperCase()};d.ef=
function(a){for(var b=0,c;c=this[b];b++)if(c.tagName===a)return!0;return!1};var e=function(a){a&&"startTag"===a.type&&(a.Za=b.test(a.tagName)||a.Za);return a},g=r,k=function(){a="</"+d.pop().tagName+">"+a},l={startTag:function(b){var e=b.tagName;"TR"===e.toUpperCase()&&d.xc("TABLE")?(a="<TBODY>"+a,m()):h.Kg&&c.test(e)&&d.ef(e)?d.xc(e)?k():(a="</"+b.tagName+">"+a,m()):b.Za||d.push(b)},endTag:function(a){d.Jd()?h.vf&&!d.xc(a.tagName)?k():d.pop():h.vf&&(g(),m())}},m=function(){var b=a,c=e(g());a=b;if(c&&
l[c.type])l[c.type](c)};r=function(){m();return e(g())}}();return{append:function(b){a+=b},eg:r,Qg:function(a){for(var b;(b=r())&&(!a[b.type]||!1!==a[b.type](b)););},clear:function(){var b=a;a="";return b},Rg:function(){return a},stack:[]}}var b=function(){var a={},b=this.document.createElement("div");b.innerHTML="<P><I></P></I>";a.Xg="<P><I></P></I>"!==b.innerHTML;b.innerHTML="<P><i><P></P></i></P>";a.Tg=2===b.childNodes.length;return a}(),c=/^<([\-A-Za-z0-9_]+)((?:\s+[\w\-]+(?:\s*=?\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,
d=/^<\/([\-A-Za-z0-9_]+)[^>]*>/,e=/([\-A-Za-z0-9_]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,g=/^(checked|compact|declare|defer|disabled|ismap|multiple|nohref|noresize|noshade|nowrap|readonly|selected)$/i;a.supports=b;a.Yg=function(a){var b={comment:function(a){return"<--"+a.content+"--\x3e"},endTag:function(a){return"</"+a.tagName+">"},atomicTag:function(a){return b.startTag(a)+a.content+b.endTag(a)},startTag:function(a){var b="<"+a.tagName,c;for(c in a.C){var d=a.C[c];
b+=" "+c+'="'+(d?d.replace(/(^|[^\\])"/g,'$1\\"'):"")+'"'}return b+(a.Za?"/>":">")},chars:function(a){return a.text}};return b[a.type](a)};a.Jg=function(a){var b={},c;for(c in a){var d=a[c];b[c]=d&&d.replace(/(^|[^\\])"/g,'$1\\"')}return b};for(var h in b)a.Xe=a.Xe||!b[h]&&h;dc=a})();(function(){function a(){}function b(a){return void 0!==a&&null!==a}function c(a,b,c){var d,e=a&&a.length||0;for(d=0;d<e;d++)b.call(c,a[d],d)}function d(a,b,c){for(var d in a)a.hasOwnProperty(d)&&b.call(c,d,a[d])}function e(a,
b){d(b,function(b,c){a[b]=c});return a}function g(a,c){a=a||{};d(c,function(c,d){b(a[c])||(a[c]=d)});return a}function h(a){try{return m.call(a)}catch(t){var b=[];c(a,function(a){b.push(a)});return b}}var k={Ie:a,Je:a,Ke:a,Le:a,Te:a,Ue:function(a){return a},done:a,error:function(a){throw a;},ig:!1},l=this;if(!l.postscribe){var m=Array.prototype.slice,n=function(){function a(a,c,d){var e="data-ps-"+c;if(2===arguments.length){var g=a.getAttribute(e);return b(g)?String(g):g}b(d)&&""!==d?a.setAttribute(e,
d):a.removeAttribute(e)}function g(b,c){var d=b.ownerDocument;e(this,{root:b,options:c,$a:d.defaultView||d.parentWindow,xa:d,Cb:dc("",{Se:!0}),bc:[b],Fc:"",Gc:d.createElement(b.nodeName),Ya:[],la:[]});a(this.Gc,"proxyof",0)}g.prototype.write=function(){[].push.apply(this.la,arguments);for(var a;!this.wb&&this.la.length;)a=this.la.shift(),"function"===typeof a?this.af(a):this.Rc(a)};g.prototype.af=function(a){var b={type:"function",value:a.name||a.toString()};this.Cc(b);a.call(this.$a,this.xa);this.Nd(b)};
g.prototype.Rc=function(a){this.Cb.append(a);for(var b,c=[],d,e;(b=this.Cb.eg())&&!(d=b&&"tagName"in b?!!~b.tagName.toLowerCase().indexOf("script"):!1)&&!(e=b&&"tagName"in b?!!~b.tagName.toLowerCase().indexOf("style"):!1);)c.push(b);this.zg(c);d&&this.Bf(b);e&&this.Cf(b)};g.prototype.zg=function(a){var b=this.Ye(a);b.qd&&(b.oc=this.Fc+b.qd,this.Fc+=b.cg,this.Gc.innerHTML=b.oc,this.wg())};g.prototype.Ye=function(a){var b=this.bc.length,d=[],e=[],g=[];c(a,function(a){d.push(a.text);if(a.C){if(!/^noscript$/i.test(a.tagName)){var c=
b++;e.push(a.text.replace(/(\/?>)/," data-ps-id="+c+" $1"));"ps-script"!==a.C.id&&"ps-style"!==a.C.id&&g.push("atomicTag"===a.type?"":"<"+a.tagName+" data-ps-proxyof="+c+(a.Za?" />":">"))}}else e.push(a.text),g.push("endTag"===a.type?a.text:"")});return{Zg:a,raw:d.join(""),qd:e.join(""),cg:g.join("")}};g.prototype.wg=function(){for(var c,d=[this.Gc];b(c=d.shift());){var e=1===c.nodeType;if(!e||!a(c,"proxyof")){e&&(this.bc[a(c,"id")]=c,a(c,"id",null));var g=c.parentNode&&a(c.parentNode,"proxyof");
g&&this.bc[g].appendChild(c)}d.unshift.apply(d,h(c.childNodes))}};g.prototype.Bf=function(a){var b=this.Cb.clear();b&&this.la.unshift(b);a.src=a.C.src||a.C.Cg;a.src&&this.Ya.length?this.wb=a:this.Cc(a);var c=this;this.yg(a,function(){c.Nd(a)})};g.prototype.Cf=function(a){var b=this.Cb.clear();b&&this.la.unshift(b);a.type=a.C.type||a.C.Dg||"text/css";this.Ag(a);b&&this.write()};g.prototype.Ag=function(a){var b=this.$e(a);this.Lf(b);a.content&&(b.styleSheet&&!b.sheet?b.styleSheet.cssText=a.content:
b.appendChild(this.xa.createTextNode(a.content)))};g.prototype.$e=function(a){var b=this.xa.createElement(a.tagName);b.setAttribute("type",a.type);d(a.C,function(a,c){b.setAttribute(a,c)});return b};g.prototype.Lf=function(a){this.Rc('<span id="ps-style"/>');var b=this.xa.getElementById("ps-style");b.parentNode.replaceChild(a,b)};g.prototype.Cc=function(a){a.Uf=this.la;this.la=[];this.Ya.unshift(a)};g.prototype.Nd=function(a){a!==this.Ya[0]?this.options.error({message:"Bad script nesting or script finished twice"}):
(this.Ya.shift(),this.write.apply(this,a.Uf),!this.Ya.length&&this.wb&&(this.Cc(this.wb),this.wb=null))};g.prototype.yg=function(a,b){var c=this.Ze(a),d=this.pg(c),e=this.options.Ie;a.src&&(c.src=a.src,this.mg(c,d?e:function(){b();e()}));try{this.Kf(c),a.src&&!d||b()}catch(B){this.options.error(B),b()}};g.prototype.Ze=function(a){var b=this.xa.createElement(a.tagName);d(a.C,function(a,c){b.setAttribute(a,c)});a.content&&(b.text=a.content);return b};g.prototype.Kf=function(a){this.Rc('<span id="ps-script"/>');
var b=this.xa.getElementById("ps-script");b.parentNode.replaceChild(a,b)};g.prototype.mg=function(a,b){function c(){a=a.onload=a.onreadystatechange=a.onerror=null}var d=this.options.error;e(a,{onload:function(){c();b()},onreadystatechange:function(){/^(loaded|complete)$/.test(a.readyState)&&(c(),b())},onerror:function(){var e={message:"remote script failed "+a.src};c();d(e);b()}})};g.prototype.pg=function(a){return!/^script$/i.test(a.nodeName)||!!(this.options.ig&&a.src&&a.hasAttribute("async"))};
return g}();l.postscribe=function(){function b(){var a=m.shift(),b;a&&(b=a[a.length-1],b.Je(),a.stream=c.apply(null,a),b.Ke())}function c(c,g,k){function l(a){a=k.Ue(a);w.write(a);k.Le(a)}w=new n(c,k);w.id=d++;w.name=k.name||w.id;var m=c.ownerDocument,q={close:m.close,open:m.open,write:m.write,writeln:m.writeln};e(m,{close:a,open:a,write:function(){return l(h(arguments).join(""))},writeln:function(){return l(h(arguments).join("")+"\n")}});var r=w.$a.onerror||a;w.$a.onerror=function(a,b,c){k.error({Ng:a+
" - "+b+":"+c});r.apply(w.$a,arguments)};w.write(g,function(){e(m,q);w.$a.onerror=r;k.done();w=null;b()});return w}var d=0,m=[],w=null;return e(function(c,d,e){"function"===typeof e&&(e={done:e});e=g(e,k);c=/^#/.test(c)?l.document.getElementById(c.substr(1)):c.Lg?c[0]:c;var h=[c,d,e];c.Xf={cancel:function(){h.stream?h.stream.abort():h[1]=a}};e.Te(h);m.push(h);w||b();return c.Xf},{streams:{},Pg:m,Eg:n})}();ec=l.postscribe}})();var D={},G=null,pc=Math.random();D.o="GTM-N6WTLHM";D.rb="2q1";var qc="www.googletagmanager.com/gtm.js";var rc=qc,sc=null,tc=null,uc=null,vc="//www.googletagmanager.com/a?id="+D.o+"&cv=7",wc={},xc={},yc=function(){var a=G.sequence||0;G.sequence=a+1;return a};var K=function(a,b,c,d){return(2===zc()||d||"http:"!=u.location.protocol?a:b)+c},zc=function(){var a=Qa(),b;if(1===a)a:{var c=rc;c=c.toLowerCase();for(var d="https://"+c,e="http://"+c,g=1,h=x.getElementsByTagName("script"),k=0;k<h.length&&100>k;k++){var l=h[k].src;if(l){l=l.toLowerCase();if(0===l.indexOf(e)){b=3;break a}1===g&&0===l.indexOf(d)&&(g=2)}}b=g}else b=a;return b};var Ac=!1;var N=function(){var a=function(a){return{toString:function(){return a}}};return{Vc:a("convert_case_to"),Wc:a("convert_false_to"),Xc:a("convert_null_to"),Yc:a("convert_true_to"),Zc:a("convert_undefined_to"),ra:a("function"),ye:a("instance_name"),ze:a("live_only"),Ae:a("malware_disabled"),Be:a("once_per_event"),md:a("once_per_load"),nd:a("setup_tags"),Ce:a("tag_id"),od:a("teardown_tags")}}();var Dc=new Aa,Ec={},Fc={},Jc={set:function(a,b){p(Gc(a,b),Ec);Hc()},get:function(a){return Ic(a,2)},reset:function(){Dc=new Aa;Ec={};Hc()}},Ic=function(a,b){return 2!=b?Dc.get(a):Kc(a)},Kc=function(a,b,c){var d=a.split("."),e=!1,g=void 0;return e?g:Mc(d)},Mc=function(a){for(var b=
Ec,c=0;c<a.length;c++){if(null===b)return!1;if(void 0===b)break;b=b[a[c]]}return b};
var Pc=function(a,b){Fc.hasOwnProperty(a)||(Dc.set(a,b),p(Gc(a,b),Ec),Hc())},Gc=function(a,b){for(var c={},d=c,e=a.split("."),g=0;g<e.length-1;g++)d=d[e[g]]={};d[e[e.length-1]]=b;return c},Hc=function(a){ta(Fc,function(b,c){Dc.set(b,c);p(Gc(b,void 0),Ec);p(Gc(b,c),Ec);a&&delete Fc[b]})};var Qc=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Rc={cl:["ecl"],customPixels:["nonGooglePixels"],ecl:["cl"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Sc={cl:["ecl"],customPixels:["customScripts","html"],ecl:["cl"],html:["customScripts"],
customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]};
var Uc=function(a){var b=Ic("gtm.whitelist");var c=b&&Fa(wa(b),Rc),d=Ic("gtm.blacklist")||Ic("tagTypeBlacklist")||[];
Tc()&&(d=wa(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&Fa(wa(d),Sc),g={};return function(h){var k=h&&h[N.ra];if(!k||"string"!=typeof k)return!0;k=k.replace(/^_*/,"");if(void 0!==g[k])return g[k];var l=xc[k]||[],m=a(k);if(b){var n;if(n=m)a:{if(0>qa(c,k))if(l&&0<l.length)for(var q=0;q<l.length;q++){if(0>qa(c,l[q])){n=!1;break a}}else{n=!1;break a}n=!0}m=n}var r=!1;if(d){var t;if(!(t=0<=qa(e,k)))a:{for(var v=l||[],w=new Aa,
A=0;A<e.length;A++)w.set(e[A],!0);for(var E=0;E<v.length;E++)if(w.get(v[E])){t=!0;break a}t=!1}r=t}return g[k]=!m||r}},Tc=function(){return Qc.test(u.location&&u.location.hostname)};var Wc=function(a){return function(b,c){if(na(c))a(b,c);else{b instanceof Vc||(b=new Vc(b));var d=b;c&&d.jc.push(c);throw d;}}},Vc=function(a){this.Tf=a;this.jc=[]};ka(Vc,Error);var Xc={ff:function(a,b){b[N.Vc]&&"string"===typeof a&&(a=1==b[N.Vc]?a.toLowerCase():a.toUpperCase());b.hasOwnProperty(N.Xc)&&null===a&&(a=b[N.Xc]);b.hasOwnProperty(N.Zc)&&void 0===a&&(a=b[N.Zc]);b.hasOwnProperty(N.Yc)&&!0===a&&(a=b[N.Yc]);b.hasOwnProperty(N.Wc)&&!1===a&&(a=b[N.Wc]);return a}};var Yc={active:!0,isWhitelisted:function(){return!0}},Zc=function(a){var b=G.zones;!b&&a&&(b=G.zones=a());return b};var $c=!1,ad=0,bd=[];function cd(a){if(!$c){var b=x.createEventObject,c="complete"==x.readyState,d="interactive"==x.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){$c=!0;for(var e=0;e<bd.length;e++)z(bd[e])}bd.push=function(){for(var a=0;a<arguments.length;a++)z(arguments[a]);return 0}}}function dd(){if(!$c&&140>ad){ad++;try{x.documentElement.doScroll("left"),cd()}catch(a){u.setTimeout(dd,50)}}}var ed=function(a){$c?a():bd.push(a)};var fd=function(){function a(a){return!na(a)||0>a?0:a}if(!G._li&&u.performance&&u.performance.timing){var b=u.performance.timing.navigationStart,c=na(Jc.get("gtm.start"))?Jc.get("gtm.start"):0;G._li={cst:a(c-b),cbt:a(tc-b)}}};var jd=!1,kd=function(){return u.GoogleAnalyticsObject&&u[u.GoogleAnalyticsObject]},ld=!1;
var pd=function(){},od=function(){return u.GoogleAnalyticsObject||"ga"},qd=!1;var xd=function(a){};
function wd(a,b){a.containerId=D.o;var c={type:"GENERIC",value:a};b.length&&(c.trace=b);return c};
var yd=function(){return"&tc="+Ob.filter(function(a){return a}).length},Hd=function(){zd&&(u.clearTimeout(zd),zd=void 0);void 0===Ad||Bd[Ad]&&!Cd||(Dd[Ad]||Ed.Pf()||0>=Fd--?Dd[Ad]=!0:(Ed.gg(),Sa(Gd()),Bd[Ad]=!0,Cd=""))},Gd=function(){var a=Ad;return void 0===a?"":[Id,Bd[a]?"":"&es=1",Jd[a],yd(),Cd,"&z=0"].join("")},Kd=function(){return[vc,"&v=3&t=t","&pid="+sa(),"&rv="+D.rb].join("")},Ld="0.005000">Math.random(),Id=Kd(),Md=function(){Id=Kd()},Bd={},Cd="",Ad=void 0,Jd={},Dd={},zd=
void 0,Ed=function(a,b){var c=0,d=0;return{Pf:function(){if(c<a)return!1;za()-d>=b&&(c=0);return c>=a},gg:function(){za()-d>=b&&(c=0);c++;d=za()}}}(2,1E3),Fd=1E3,Nd=function(a,b){if(Ld&&!Dd[a]&&Ad!==a){Hd();Ad=a;Cd="";var c;c=0===b.indexOf("gtm.")?encodeURIComponent(b):"*";Jd[a]="&e="+c+"&eid="+a;zd||(zd=u.setTimeout(Hd,500))}},Od=function(a,b,c){if(Ld&&!Dd[a]&&b){a!==Ad&&(Hd(),Ad=a);var d=c+String(b[N.ra]||"").replace(/_/g,"");Cd=Cd?Cd+"."+d:"&tr="+d;zd||(zd=u.setTimeout(Hd,500));2022<=Gd().length&&
Hd()}};function Pd(a,b,c,d,e){var g=Ob[a],h=Qd(a,b,c,d,e);if(!h)return null;var k=Wb(g[N.nd],d.fa,[],la);if(k&&k.length){var l=k[0];h=Pd(l.index,b,{H:h,M:1===l.wd?c.terminate:h,terminate:c.terminate},d,e)}return h}
function Qd(a,b,c,d,e){function g(){if(h[N.Ae])l();else{var b=Xb(h,d.fa,[],Wc(function(a){xd(a)})),c=!1;b.vtp_gtmOnSuccess=function(){if(!c){c=!0;Od(d.id,Ob[a],"5");k()}};b.vtp_gtmOnFailure=function(){if(!c){c=!0;Od(d.id,Ob[a],"6");l()}};b.vtp_gtmTagId=h.tag_id;Od(d.id,h,"1");var e=!1,
g=function(a,b){if(!e){a instanceof Vc||(a=new Vc(a));var g=a;b&&g.jc.push(b);throw g;}xd(a);Od(d.id,h,"7");c||(c=!0,l())};try{Vb(b,g)}catch(P){try{e=!0,g(P)}catch(F){}}}}var h=
Ob[a],k=c.H,l=c.M,m=c.terminate;if(d.fa(h))return null;var n=Wb(h[N.od],d.fa,[],la);if(n&&n.length){var q=n[0],r=Pd(q.index,b,{H:k,M:l,terminate:m},d,e);if(!r)return null;k=r;l=2===q.wd?m:r}if(h[N.md]||h[N.Be]){var t=h[N.md]?Pb:b,v=k,w=l;if(!t[a]){g=Ca(g);var A=Rd(a,t,g);k=A.H;l=A.M}return function(){t[a](v,w)}}return g}function Rd(a,b,c){var d=[],e=[];b[a]=Sd(d,e,c);return{H:function(){b[a]=Td;for(var c=0;c<d.length;c++)d[c]()},M:function(){b[a]=Ud;for(var c=0;c<e.length;c++)e[c]()}}}
function Sd(a,b,c){return function(d,e){a.push(d);b.push(e);c()}}function Td(a){a()}function Ud(a,b){b()};function Vd(a){var b=0,c=0,d=!1;return{add:function(){c++;return Ca(function(){b++;d&&b>=c&&a()})},Qe:function(){d=!0;b>=c&&a()}}}var Yd=function(a){for(var b=Vd(a.callback),c=[],d=[],e=0;e<Ob.length;e++)if(a.Wa[e]){var g=Ob[e];var h=b.add();try{var k=Pd(e,c,{H:h,M:h,terminate:h},a,e);k?d.push({Xd:e,b:Yb(g),uf:k}):(Wd(e,a),h())}catch(m){h()}}b.Qe();d.sort(Xd);for(var l=0;l<d.length;l++)d[l].uf();return 0<d.length};
function Xd(a,b){var c,d=b.b,e=a.b;c=d>e?1:d<e?-1:0;var g;if(0!==c)g=c;else{var h=a.Xd,k=b.Xd;g=h>k?1:h<k?-1:0}return g}function Wd(a,b){if(!Ld)return;var c=function(a){var d=b.fa(Ob[a])?"3":"4",g=Wb(Ob[a][N.nd],b.fa,[],la);g&&g.length&&c(g[0].index);Od(b.id,Ob[a],d);var h=Wb(Ob[a][N.od],b.fa,[],la);h&&h.length&&c(h[0].index)};c(a);}
var Zd=!1,$d=function(a,b,c,d){if("gtm.js"==b){if(Zd)return!1;Zd=!0}Nd(a,b);var e=Uc(c),g={id:a,name:b,callback:d||la,fa:e,Wa:[]};g.Wa=cc(e,Wc(function(a){xd(a)}));var h=Yd(g);"gtm.js"!==b&&"gtm.sync"!==b||pd();if(!h)return h;for(var k={__cl:!0,__ecl:!0,__evl:!0,__fsl:!0,__hl:!0,__jel:!0,__lcl:!0,__sdl:!0,__tl:!0,__ytl:!0},l=0;l<g.Wa.length;l++)if(g.Wa[l]){var m=
Ob[l];if(m&&!k[m[N.ra]])return!0}return!1};var O={Ob:"event_callback",Qb:"event_timeout"};var be={};var ce=/[A-Z]+/,de=/\s/,ee=function(a){if(f(a)&&(a=ya(a),!de.test(a))){var b=a.indexOf("-");if(!(0>b)){var c=a.substring(0,b);if(ce.test(c)){for(var d=a.substring(b+1).split("/"),e=0;e<d.length;e++)if(!d[e])return;return{id:a,prefix:c,containerId:c+"-"+d[0],da:d}}}}},ge=function(a){for(var b={},c=0;c<a.length;++c){var d=ee(a[c]);d&&(b[d.id]=d)}fe(b);var e=[];ta(b,function(a,b){e.push(b)});return e};
function fe(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];"AW"===d.prefix&&d.da[1]&&b.push(d.containerId)}for(var e=0;e<b.length;++e)delete a[b[e]]};var he=null,ie={},je={},ke,le=function(a,b){var c={event:a};b&&(c.eventModel=p(b),b[O.Ob]&&(c.eventCallback=b[O.Ob]),b[O.Qb]&&(c.eventTimeout=b[O.Qb]));return c};
var qe={config:function(a){},event:function(a){var b=a[1];if(f(b)&&!(3<a.length)){var c;if(2<a.length){if(!Ka(a[2]))return;
c=a[2]}var d=le(b,c);return d}},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}},policy:function(a){if(3===a.length){var b=a[1],c=a[2];be[b]||(be[b]=[]);be[b].push(c)}},set:function(a){var b;2==a.length&&Ka(a[1])?b=p(a[1]):3==a.length&&f(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b.eventModel=p(b),b.event="gtag.set",b._clear=!0,b}},re={policy:!0};var se=function(){return!1};var xe=function(a){this.vg=a};xe.prototype.Af=function(){return this.vg};var ye=function(a){return!a||"object"!==Ha(a)||Ka(a)?!1:"getUntrustedUpdateValue"in a};xe.prototype.getUntrustedUpdateValue=xe.prototype.Af;var ze=!1,Ae=[];function Be(){if(!ze){ze=!0;for(var a=0;a<Ae.length;a++)z(Ae[a])}}var Ce=function(a){ze?z(a):Ae.push(a)};var De=[],Ee=!1;function Fe(a){var b=a.eventCallback,c=Ca(function(){ma(b)&&z(function(){b(D.o)})}),d=a.eventTimeout;d&&u.setTimeout(c,Number(d));return c}
var Ge=function(a){return u["dataLayer"].push(a)},Ie=function(a){var b=a._clear;ta(a,function(a,c){"_clear"!==a&&(b&&Pc(a,void 0),Pc(a,c))});var c=a.event;if(!c)return!1;var d=a["gtm.uniqueEventId"];d||(d=yc(),a["gtm.uniqueEventId"]=d,Pc("gtm.uniqueEventId",d));uc=c;var e=He(a);uc=null;if(!sc){sc=a["gtm.start"];}return e};
function He(a){var b=a.event,c=a["gtm.uniqueEventId"],d,e=G.zones;d=e?e.checkState(D.o,c):Yc;if(!d.active)return!1;var g=Fe(a);return $d(c,b,d.isWhitelisted,g)?!0:!1}
var Je=function(){for(var a=!1;!Ee&&0<De.length;){Ee=!0;delete Ec.eventModel;Hc();var b=De.shift();if(null!=b){var c=ye(b);if(c){var d=b;b=ye(d)?d.getUntrustedUpdateValue():void 0;for(var e=["gtm.whitelist","gtm.blacklist","tagTypeBlacklist"],g=0;g<e.length;g++){var h=e[g],k=Ic(h,1);if(oa(k)||Ka(k))k=p(k);Fc[h]=k}}try{if(ma(b))try{b.call(Jc)}catch(w){}else if(oa(b)){var l=b;if(f(l[0])){var m=
l[0].split("."),n=m.pop(),q=l.slice(1),r=Ic(m.join("."),2);if(void 0!==r&&null!==r)try{r[n].apply(r,q)}catch(w){}}}else{var t=b;if(t&&("[object Arguments]"==Object.prototype.toString.call(t)||Object.prototype.hasOwnProperty.call(t,"callee"))){a:{if(b.length&&f(b[0])){var v=qe[b[0]];if(v&&(!c||!re[b[0]])){b=v(b);break a}}b=void 0}if(!b){Ee=!1;continue}}a=Ie(b)||a}}finally{c&&Hc(!0)}}Ee=!1}
return!a},Ke=function(){var a=Je();try{var b=D.o,c=u["dataLayer"].hide;if(c&&void 0!==c[b]&&c.end){c[b]=!1;var d=!0,e;for(e in c)if(c.hasOwnProperty(e)&&!0===c[e]){d=!1;break}d&&(c.end(),c.end=null)}}catch(g){}return a},Le=function(){var a=Na("dataLayer",[]),b=Na("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};ed(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Ce(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b;
if(0<G.SANDBOXED_JS_SEMAPHORE){b=[];for(var e=0;e<arguments.length;e++)b[e]=new xe(arguments[e])}else b=[].slice.call(arguments,0);c.apply(a,b);for(De.push.apply(De,b);300<this.length;)this.shift();return Je()};De.push.apply(De,a.slice(0));z(Ke)};var Ne=function(a){return Me?x.querySelectorAll(a):null},Oe=function(a,b){if(!Me)return null;if(Element.prototype.closest)try{return a.closest(b)}catch(e){return null}var c=Element.prototype.matches||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector,d=a;if(!x.documentElement.contains(d))return null;do{try{if(c.call(d,b))return d}catch(e){break}d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType);
return null},Pe=!1;if(x.querySelectorAll)try{var Qe=x.querySelectorAll(":root");Qe&&1==Qe.length&&Qe[0]==x.documentElement&&(Pe=!0)}catch(a){}var Me=Pe;var Re;var nf={};nf.nb=new String("undefined");
var of=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===nf.nb?b:a[d]);return c.join("")}};of.prototype.toString=function(){return this.resolve("undefined")};of.prototype.valueOf=of.prototype.toString;nf.De=of;nf.$b={};nf.kf=function(a){return new of(a)};var pf={};nf.hg=function(a,b){var c=yc();pf[c]=[a,b];return c};nf.td=function(a){var b=a?0:1;return function(a){var c=pf[a];if(c&&"function"===typeof c[b])c[b]();pf[a]=void 0}};nf.Nf=function(a){for(var b=!1,c=!1,
d=2;d<a.length;d++)b=b||8===a[d],c=c||16===a[d];return b&&c};nf.Yf=function(a){if(a===nf.nb)return a;var b=yc();nf.$b[b]=a;return'google_tag_manager["'+D.o+'"].macro('+b+")"};nf.Rf=function(a,b,c){a instanceof nf.De&&(a=a.resolve(nf.hg(b,c)),b=la);return{oc:a,H:b}};var qf=function(a,b,c){var d={event:b,"gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||Ua(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};c&&(d["gtm.triggers"]=c.join(","));d["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||a.src||a.code||a.codebase||"";return d},rf=function(a){G.hasOwnProperty("autoEventsSettings")||(G.autoEventsSettings={});var b=G.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},sf=
function(a,b,c,d){var e=rf(a),g=Ba(e,b,d);e[b]=c(g)},tf=function(a,b,c){var d=rf(a);return Ba(d,b,c)};var uf=function(){for(var a=La.userAgent+(x.cookie||"")+(x.referrer||""),b=a.length,c=u.history.length;0<c;)a+=c--^b++;var d=1,e,g,h;if(a)for(d=0,g=a.length-1;0<=g;g--)h=a.charCodeAt(g),d=(d<<6&268435455)+h+(h<<14),e=d&266338304,d=0!=e?d^e>>21:d;return[Math.round(2147483647*Math.random())^d&2147483647,Math.round(za()/1E3)].join(".")},xf=function(a,b,c,d){var e=vf(b);return hb(a,e,wf(c),d)},vf=function(a){if(!a)return 1;a=0===a.indexOf(".")?a.substr(1):a;return a.split(".").length},wf=function(a){if(!a||
"/"===a)return 1;"/"!==a[0]&&(a="/"+a);"/"!==a[a.length-1]&&(a+="/");return a.split("/").length-1};function yf(a,b){var c=""+vf(a),d=wf(b);1<d&&(c+="-"+d);return c};var zf=["1"],Af={},Ef=function(a,b,c,d){var e=Bf(a);Af[e]||Cf(e,b,c)||(Df(e,uf(),b,c,d),Cf(e,b,c))};function Df(a,b,c,d,e){var g;g=["1",yf(d,c),b].join(".");mb(a,g,c,d,0==e?void 0:new Date(za()+1E3*(void 0==e?7776E3:e)))}function Cf(a,b,c){var d=xf(a,b,c,zf);d&&(Af[a]=d);return d}function Bf(a){return(a||"_gcl")+"_au"};var Ff=function(){for(var a=[],b=x.cookie.split(";"),c=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,d=0;d<b.length;d++){var e=b[d].match(c);e&&a.push({Nc:e[1],value:e[2]})}var g={};if(!a||!a.length)return g;for(var h=0;h<a.length;h++){var k=a[h].value.split(".");"1"==k[0]&&3==k.length&&k[1]&&(g[a[h].Nc]||(g[a[h].Nc]=[]),g[a[h].Nc].push({timestamp:k[1],xf:k[2]}))}return g};function Gf(){for(var a=Hf,b={},c=0;c<a.length;++c)b[a[c]]=c;return b}function If(){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";a+=a.toLowerCase()+"0123456789-_";return a+"."}
var Hf,Jf,Kf=function(a){Hf=Hf||If();Jf=Jf||Gf();for(var b=[],c=0;c<a.length;c+=3){var d=c+1<a.length,e=c+2<a.length,g=a.charCodeAt(c),h=d?a.charCodeAt(c+1):0,k=e?a.charCodeAt(c+2):0,l=g>>2,m=(g&3)<<4|h>>4,n=(h&15)<<2|k>>6,q=k&63;e||(q=64,d||(n=64));b.push(Hf[l],Hf[m],Hf[n],Hf[q])}return b.join("")},Lf=function(a){function b(b){for(;d<a.length;){var c=a.charAt(d++),e=Jf[c];if(null!=e)return e;if(!/^[\s\xa0]*$/.test(c))throw Error("Unknown base64 encoding at char: "+c);}return b}Hf=Hf||If();Jf=Jf||
Gf();for(var c="",d=0;;){var e=b(-1),g=b(0),h=b(64),k=b(64);if(64===k&&-1===e)return c;c+=String.fromCharCode(e<<2|g>>4);64!=h&&(c+=String.fromCharCode(g<<4&240|h>>2),64!=k&&(c+=String.fromCharCode(h<<6&192|k)))}};var Mf;function Nf(a,b){if(!a||b===x.location.hostname)return!1;for(var c=0;c<a.length;c++)if(a[c]instanceof RegExp){if(a[c].test(b))return!0}else if(0<=b.indexOf(a[c]))return!0;return!1}var Of=function(){var a=Na("google_tag_data",{}),b=a.gl;b&&b.decorators||(b={decorators:[]},a.gl=b);return b};var Pf=/(.*?)\*(.*?)\*(.*)/,Qf=/^https?:\/\/([^\/]*?)\.?cdn\.ampproject\.org\/?(.*)/,Rf=/^(?:www\.|m\.|amp\.)+/,Sf=/([^?#]+)(\?[^#]*)?(#.*)?/,Tf=/(.*?)(^|&)_gl=([^&]*)&?(.*)/,Vf=function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];void 0!==d&&d===d&&null!==d&&"[object Object]"!==d.toString()&&(b.push(c),b.push(Kf(String(d))))}var e=b.join("*");return["1",Uf(e),e].join("*")},Uf=function(a,b){var c=[window.navigator.userAgent,(new Date).getTimezoneOffset(),window.navigator.userLanguage||
window.navigator.language,Math.floor((new Date).getTime()/60/1E3)-(void 0===b?0:b),a].join("*"),d;if(!(d=Mf)){for(var e=Array(256),g=0;256>g;g++){for(var h=g,k=0;8>k;k++)h=h&1?h>>>1^3988292384:h>>>1;e[g]=h}d=e}Mf=d;for(var l=4294967295,m=0;m<c.length;m++)l=l>>>8^Mf[(l^c.charCodeAt(m))&255];return((l^-1)>>>0).toString(36)},Xf=function(){return function(a){var b=db(u.location.href),c=b.search.replace("?",""),d=ab(c,"_gl",!0)||"";a.query=Wf(d)||{};var e=C(b,"fragment").match(Tf);a.fragment=Wf(e&&e[3]||
"")||{}}},Wf=function(a){var b;b=void 0===b?3:b;try{if(a){var c;a:{for(var d=a,e=0;3>e;++e){var g=Pf.exec(d);if(g){c=g;break a}d=decodeURIComponent(d)}c=void 0}var h=c;if(h&&"1"===h[1]){var k=h[3],l;a:{for(var m=h[2],n=0;n<b;++n)if(m===Uf(k,n)){l=!0;break a}l=!1}if(l){for(var q={},r=k?k.split("*"):[],t=0;t<r.length;t+=2)q[r[t]]=Lf(r[t+1]);return q}}}}catch(v){}};
function Yf(a,b,c){function d(a){var b=a,c=Tf.exec(b),d=b;if(c){var e=c[2],g=c[4];d=c[1];g&&(d=d+e+g)}a=d;var h=a.charAt(a.length-1);a&&"&"!==h&&(a+="&");return a+l}c=void 0===c?!1:c;var e=Sf.exec(b);if(!e)return"";var g=e[1],h=e[2]||"",k=e[3]||"",l="_gl="+a;c?k="#"+d(k.substring(1)):h="?"+d(h.substring(1));return""+g+h+k}
function Zf(a,b,c){for(var d={},e={},g=Of().decorators,h=0;h<g.length;++h){var k=g[h];(!c||k.forms)&&Nf(k.domains,b)&&(k.fragment?Da(e,k.callback()):Da(d,k.callback()))}if(Ea(d)){var l=Vf(d);if(c){if(a&&a.action){var m=(a.method||"").toLowerCase();if("get"===m){for(var n=a.childNodes||[],q=!1,r=0;r<n.length;r++){var t=n[r];if("_gl"===t.name){t.setAttribute("value",l);q=!0;break}}if(!q){var v=x.createElement("input");v.setAttribute("type","hidden");v.setAttribute("name","_gl");v.setAttribute("value",
l);a.appendChild(v)}}else if("post"===m){var w=Yf(l,a.action);Za.test(w)&&(a.action=w)}}}else $f(l,a,!1)}if(!c&&Ea(e)){var A=Vf(e);$f(A,a,!0)}}function $f(a,b,c){if(b.href){var d=Yf(a,b.href,void 0===c?!1:c);Za.test(d)&&(b.href=d)}}
var ag=function(a){try{var b;a:{for(var c=a.target||a.srcElement||{},d=100;c&&0<d;){if(c.href&&c.nodeName.match(/^a(?:rea)?$/i)){b=c;break a}c=c.parentNode;d--}b=null}var e=b;if(e){var g=e.protocol;"http:"!==g&&"https:"!==g||Zf(e,e.hostname,!1)}}catch(h){}},bg=function(a){try{var b=a.target||a.srcElement||{};if(b.action){var c=C(db(b.action),"host");Zf(b,c,!0)}}catch(d){}},cg=function(a,b,c,d){var e=Of();e.init||(y(x,"mousedown",ag),y(x,"keyup",ag),y(x,"submit",bg),e.init=!0);var g={callback:a,domains:b,
fragment:"fragment"===c,forms:!!d};Of().decorators.push(g)},dg=function(){var a=x.location.hostname,b=Qf.exec(x.referrer);if(!b)return!1;var c=b[2],d=b[1],e="";if(c){var g=c.split("/"),h=g[1];e="s"===h?decodeURIComponent(g[2]):decodeURIComponent(h)}else if(d){if(0===d.indexOf("xn--"))return!1;e=d.replace(/-/g,".").replace(/\.\./g,"-")}return a.replace(Rf,"")===e.replace(Rf,"")},eg=function(a,b){return!1===a?!1:a||b||dg()};var fg=/^\w+$/,gg=/^[\w-]+$/,hg=/^~?[\w-]+$/,ig={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha"};function jg(a){return a&&"string"==typeof a&&a.match(fg)?a:"_gcl"}var lg=function(){var a=db(u.location.href),b=C(a,"query",!1,void 0,"gclid"),c=C(a,"query",!1,void 0,"gclsrc"),d=C(a,"query",!1,void 0,"dclid");if(!b||!c){var e=a.hash.replace("#","");b=b||ab(e,"gclid",void 0);c=c||ab(e,"gclsrc",void 0)}return kg(b,c,d)};
function kg(a,b,c){var d={},e=function(a,b){d[b]||(d[b]=[]);d[b].push(a)};if(void 0!==a&&a.match(gg))switch(b){case void 0:e(a,"aw");break;case "aw.ds":e(a,"aw");e(a,"dc");break;case "ds":e(a,"dc");break;case "gf":e(a,"gf");break;case "ha":e(a,"ha")}c&&e(c,"dc");return d}
function mg(a,b,c){function d(a,b){var c=ng(a,e);c&&mb(c,b,h,g,l,!0)}b=b||{};var e=jg(b.prefix),g=b.domain||"auto",h=b.path||"/",k=void 0==b.Kd?7776E3:b.Kd;c=c||za();var l=0==k?void 0:new Date(c+1E3*k),m=Math.round(c/1E3),n=function(a){return["GCL",m,a].join(".")};a.aw&&(!0===b.ah?d("aw",n("~"+a.aw[0])):d("aw",n(a.aw[0])));a.dc&&d("dc",n(a.dc[0]));a.gf&&d("gf",n(a.gf[0]));a.ha&&d("ha",n(a.ha[0]))}
var ng=function(a,b){var c=ig[a];if(void 0!==c)return b+c},og=function(a){var b=a.split(".");return 3!==b.length||"GCL"!==b[0]?0:1E3*(Number(b[1])||0)};function pg(a){var b=a.split(".");if(3==b.length&&"GCL"==b[0]&&b[1])return b[2]}
var qg=function(a,b,c,d,e){if(oa(b)){var g=jg(e);cg(function(){for(var b={},c=0;c<a.length;++c){var d=ng(a[c],g);if(d){var e=eb(d,x.cookie);e.length&&(b[d]=e.sort()[e.length-1])}}return b},b,c,d)}},rg=function(a){return a.filter(function(a){return hg.test(a)})},sg=function(a,b){for(var c=jg(b&&b.prefix),d={},e=0;e<a.length;e++)ig[a[e]]&&(d[a[e]]=ig[a[e]]);ta(d,function(a,d){var e=eb(c+d,x.cookie);if(e.length){var g=e[0],h=og(g),n={};n[a]=[pg(g)];mg(n,b,h)}})};var tg=/^\d+\.fls\.doubleclick\.net$/;function ug(a){var b=db(u.location.href),c=C(b,"host",!1);if(c&&c.match(tg)){var d=C(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function vg(a,b){if("aw"==a||"dc"==a){var c=ug("gcl"+a);if(c)return c.split(".")}var d=jg(b);if("_gcl"==d){var e;e=lg()[a]||[];if(0<e.length)return e}var g=ng(a,d),h;if(g){var k=[];if(x.cookie){var l=eb(g,x.cookie);if(l&&0!=l.length){for(var m=0;m<l.length;m++){var n=pg(l[m]);n&&-1===qa(k,n)&&k.push(n)}h=rg(k)}else h=k}else h=k}else h=[];return h}
var wg=function(){var a=ug("gac");if(a)return decodeURIComponent(a);var b=Ff(),c=[];ta(b,function(a,b){for(var d=[],e=0;e<b.length;e++)d.push(b[e].xf);d=rg(d);d.length&&c.push(a+":"+d.join(","))});return c.join(";")},xg=function(a,b,c,d,e){Ef(b,c,d,e);var g=Af[Bf(b)],h=lg().dc||[],k=!1;if(g&&0<h.length){var l=G.joined_au=G.joined_au||{},m=b||"_gcl";if(!l[m])for(var n=0;n<h.length;n++){var q="https://adservice.google.com/ddm/regclk",r=q=q+"?gclid="+h[n]+"&auiddc="+g;La.sendBeacon&&La.sendBeacon(r)||Sa(r);k=l[m]=
!0}}if(k&&g){var t=Bf(b),v=Af[t];v&&Df(t,v,c,d,e)}};var yg;if(3===D.rb.length)yg="g";else{var zg="G";yg=zg}
var Ag={"":"n",UA:"u",AW:"a",DC:"d",G:"e",GF:"f",HA:"h",GTM:yg},Bg=function(a){var b=D.o.split("-"),c=b[0].toUpperCase(),d=Ag[c]||"i",e=a&&"GTM"===c?b[1]:"",g;if(3===D.rb.length){var h=void 0;g="2"+(h||"w")}else g="";return g+d+D.rb+e};var Ig=!!u.MutationObserver,Jg=void 0,Kg=function(a){if(!Jg){var b=function(){var a=x.body;if(a)if(Ig)(new MutationObserver(function(){for(var a=0;a<Jg.length;a++)z(Jg[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;y(a,"DOMNodeInserted",function(){b||(b=!0,z(function(){b=!1;for(var a=0;a<Jg.length;a++)z(Jg[a])}))})}};Jg=[];x.body?b():z(b)}Jg.push(a)};var bh=u.clearTimeout,ch=u.setTimeout,Q=function(a,b,c){if(se()){b&&z(b)}else return Pa(a,b,c)},dh=function(){return new Date},R=function(){return u.location.href},eh=function(a){return C(db(a),"fragment")},fh=function(a){return cb(db(a))},T=function(a,b){return Ic(a,b||2)},gh=function(a,b,c){b&&(a.eventCallback=b,c&&(a.eventTimeout=c));return Ge(a)},hh=function(a,b){u[a]=b},U=function(a,b,c){b&&(void 0===u[a]||c&&
!u[a])&&(u[a]=b);return u[a]},ih=function(a,b,c){return eb(a,b,void 0===c?!0:!!c)},jh=function(a,b,c,d){var e={prefix:a,path:b,domain:c,Kd:d},g=lg();mg(g,e);sg(["aw"],e);sg(["dc"],e);},kh=function(a,b,c,d,e){var g=Xf(),h=Of();h.data||(h.data=
{query:{},fragment:{}},g(h.data));var k={},l=h.data;l&&(Da(k,l.query),Da(k,l.fragment));for(var m=jg(b),n=0;n<a.length;++n){var q=a[n];if(void 0!==ig[q]){var r=ng(q,m),t=k[r];if(t){var v=Math.min(og(t),za()),w;b:{for(var A=v,E=eb(r,x.cookie),B=0;B<E.length;++B)if(og(E[B])>A){w=!0;break b}w=!1}w||mb(r,t,c,d,0==e?void 0:new Date(v+1E3*(null==e?7776E3:e)),!0)}}}var H={prefix:b,path:c,domain:d};mg(kg(k.gclid,k.gclsrc),H);},lh=function(a,b,c,d,e){
qg(a,b,c,d,e);},mh=function(a,b){if(se()){b&&z(b)}else Ra(a,b)},nh=function(a){return!!tf(a,"init",!1)},oh=function(a){rf(a).init=!0},ph=function(a,b,c){var d=(void 0===c?0:c)?"www.googletagmanager.com/gtag/js":rc;d+="?id="+encodeURIComponent(a)+"&l=dataLayer";b&&ta(b,function(a,b){b&&(d+="&"+a+"="+encodeURIComponent(b))});Q(K("https://","http://",d))};
var rh=nf.Rf;
var sh=new Aa;function th(a,b){function c(a){var b=db(a),c=C(b,"protocol"),d=C(b,"host",!0),e=C(b,"port"),g=C(b,"path").toLowerCase().replace(/\/$/,"");if(void 0===c||"http"==c&&"80"==e||"https"==c&&"443"==e)c="web",e="default";return[c,d,e,g]}for(var d=c(String(a)),e=c(String(b)),g=0;g<d.length;g++)if(d[g]!==e[g])return!1;return!0}
function uh(a){var b=a.arg0,c=a.arg1;if(a.any_of&&oa(c)){for(var d=0;d<c.length;d++)if(uh({"function":a["function"],arg0:b,arg1:c[d]}))return!0;return!1}switch(a["function"]){case "_cn":return 0<=String(b).indexOf(String(c));case "_css":var e;a:{if(b){var g=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"];try{for(var h=0;h<g.length;h++)if(b[g[h]]){e=b[g[h]](c);break a}}catch(w){}}e=!1}return e;case "_ew":var k,l;k=String(b);l=String(c);var m=k.length-
l.length;return 0<=m&&k.indexOf(l,m)==m;case "_eq":return String(b)==String(c);case "_ge":return Number(b)>=Number(c);case "_gt":return Number(b)>Number(c);case "_lc":var n;n=String(b).split(",");return 0<=qa(n,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":var q;var r=a.ignore_case?"i":void 0;try{var t=String(c)+r,v=sh.get(t);v||(v=new RegExp(c,r),sh.set(t,v));q=v.test(b)}catch(w){q=!1}return q;case "_sw":return 0==String(b).indexOf(String(c));
case "_um":return th(b,c)}return!1};var wh=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var xh={},yh=encodeURI,W=encodeURIComponent,zh=Sa;var Ah=function(a,b){if(!a)return!1;var c=C(db(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var g=c.length-e.length;0<g&&"."!=e.charAt(0)&&(g--,e="."+e);if(0<=g&&c.indexOf(e,g)==g)return!0}}return!1};
var X=function(a,b,c){for(var d={},e=!1,g=0;a&&g<a.length;g++)a[g]&&a[g].hasOwnProperty(b)&&a[g].hasOwnProperty(c)&&(d[a[g][b]]=a[g][c],e=!0);return e?d:null};xh.Of=function(){var a=!1;return a};var ji=function(a,b,c,d){this.n=a;this.t=b;this.p=c;this.d=d},ki=function(){this.c=1;this.e=[];this.p=null};function li(a){var b=G,c=b.gss=b.gss||{};return c[a]=c[a]||new ki}var mi=function(a,b){li(a).p=b},ni=function(a){var b=li(a),c=b.p;if(c){var d=b.e,e=[];b.e=[];var g=function(a){for(var b=0;b<a.length;b++)try{var d=a[b];d.d?(d.d=!1,e.push(d)):c(d.n,d.t,d.p)}catch(m){}};g(d);g(e)}};var pi=function(){var a=u.gaGlobal=u.gaGlobal||{};a.hid=a.hid||sa();return a.hid};var Ei=window,Fi=document,Gi=function(a){var b=Ei._gaUserPrefs;if(b&&b.ioo&&b.ioo()||a&&!0===Ei["ga-disable-"+a])return!0;try{var c=Ei.external;if(c&&c._gaUserPrefs&&"oo"==c._gaUserPrefs)return!0}catch(g){}for(var d=eb("AMP_TOKEN",Fi.cookie,!0),e=0;e<d.length;e++)if("$OPT_OUT"==d[e])return!0;return Fi.getElementById("__gaOptOutExtension")?!0:!1};var Ni=function(a,b,c){Mi(a);var d=Math.floor(za()/1E3);li(a).e.push(new ji(b,d,c,void 0));ni(a)},Oi=function(a,b,c){Mi(a);var d=Math.floor(za()/1E3);li(a).e.push(new ji(b,d,c,!0))},Mi=function(a){if(1===li(a).c){li(a).c=2;var b=encodeURIComponent(a);Pa(("http:"!=u.location.protocol?"https:":"http:")+("//www.googletagmanager.com/gtag/js?id="+b+"&l=dataLayer&cx=c"))}},Qi=function(a,b){},Pi=function(a,b){};var Y={a:{}};
Y.a.e=["google"],function(){(function(a){Y.__e=a;Y.__e.g="e";Y.__e.h=!0;Y.__e.b=0})(function(){return uc})}();
Y.a.f=["google"],function(){(function(a){Y.__f=a;Y.__f.g="f";Y.__f.h=!0;Y.__f.b=0})(function(a){var b=T("gtm.referrer",1)||x.referrer;return b?a.vtp_component&&"URL"!=a.vtp_component?C(db(String(b)),a.vtp_component,a.vtp_stripWww,a.vtp_defaultPages,a.vtp_queryKey):fh(String(b)):String(b)})}();

Y.a.u=["google"],function(){var a=function(a){return{toString:function(){return a}}};(function(a){Y.__u=a;Y.__u.g="u";Y.__u.h=!0;Y.__u.b=0})(function(b){var c;c=(c=b.vtp_customUrlSource?b.vtp_customUrlSource:T("gtm.url",1))||R();var d=b[a("vtp_component")];if(!d||"URL"==d)return fh(String(c));var e=db(String(c)),g;if("QUERY"==d&&b[a("vtp_multiQueryKeys")])a:{var h=b[a("vtp_queryKey")],k;k=oa(h)?h:String(h||"").replace(/\s+/g,"").split(",");for(var l=0;l<k.length;l++){var m=C(e,"QUERY",void 0,void 0,
k[l]);if(null!=m){g=m;break a}}g=void 0}else g=C(e,d,"HOST"==d?b[a("vtp_stripWww")]:void 0,"PATH"==d?b[a("vtp_defaultPages")]:void 0,"QUERY"==d?b[a("vtp_queryKey")]:void 0);return g})}();








Y.a.html=["customScripts"],function(){function a(b,c,g,h){return function(){try{if(0<c.length){var d=c.shift(),e=a(b,c,g,h);if("SCRIPT"==String(d.nodeName).toUpperCase()&&"text/gtmscript"==d.type){var m=x.createElement("script");m.async=!1;m.type="text/javascript";m.id=d.id;m.text=d.text||d.textContent||d.innerHTML||"";d.charset&&(m.charset=d.charset);var n=d.getAttribute("data-gtmsrc");n&&(m.src=n,Oa(m,e));b.insertBefore(m,null);n||e()}else if(d.innerHTML&&0<=d.innerHTML.toLowerCase().indexOf("<script")){for(var q=
[];d.firstChild;)q.push(d.removeChild(d.firstChild));b.insertBefore(d,null);a(d,q,e,h)()}else b.insertBefore(d,null),e()}else g()}catch(r){z(h)}}}var b=function(a,b,c){ed(function(){var d,e=G;e.postscribe||(e.postscribe=ec);d=e.postscribe;var g={done:b},m=x.createElement("div");m.style.display="none";m.style.visibility="hidden";x.body.appendChild(m);try{d(m,a,g)}catch(n){z(c)}})};var c=function(d){if(x.body){var e=
d.vtp_gtmOnFailure,g=rh(d.vtp_html,d.vtp_gtmOnSuccess,e),h=g.oc,k=g.H;if(d.vtp_useIframe){}else d.vtp_supportDocumentWrite?b(h,k,e):a(x.body,Xa(h),k,e)()}else ch(function(){c(d)},
200)};Y.__html=c;Y.__html.g="html";Y.__html.h=!0;Y.__html.b=0}();



var Ri={};Ri.macro=function(a){if(nf.$b.hasOwnProperty(a))return nf.$b[a]},Ri.onHtmlSuccess=nf.td(!0),Ri.onHtmlFailure=nf.td(!1);Ri.dataLayer=Jc;Ri.callback=function(a){wc.hasOwnProperty(a)&&ma(wc[a])&&wc[a]();delete wc[a]};Ri.Ve=function(){G[D.o]=Ri;xc=Y.a;Sb=Sb||nf;Tb=Xc};
Ri.Jf=function(){G=u.google_tag_manager=u.google_tag_manager||{};if(G[D.o]){var a=G.zones;a&&a.unregisterChild(D.o)}else{for(var b=data.resource||{},c=b.macros||[],d=0;d<c.length;d++)Lb.push(c[d]);for(var e=b.tags||[],g=0;g<e.length;g++)Ob.push(e[g]);for(var h=b.predicates||[],k=0;k<h.length;k++)Nb.push(h[k]);for(var l=b.rules||[],m=0;m<l.length;m++){for(var n=l[m],q={},r=0;r<n.length;r++)q[n[r][0]]=
Array.prototype.slice.call(n[r],1);Mb.push(q)}Qb=Y;Rb=uh;Ri.Ve();Le();$c=!1;ad=0;if("interactive"==x.readyState&&!x.createEventObject||"complete"==x.readyState)cd();else{y(x,"DOMContentLoaded",cd);y(x,"readystatechange",cd);if(x.createEventObject&&x.documentElement.doScroll){var t=!0;try{t=!u.frameElement}catch(E){}t&&dd()}y(u,"load",cd)}ze=!1;"complete"===x.readyState?Be():y(u,"load",Be);a:{if(!Ld)break a;u.setInterval(Md,864E5);}tc=(new Date).getTime();}};(0,Ri.Jf)();

})()
