#### Exclude
exclude: [".rvmrc", ".rbenv-version", "README.md", "README_en.md", "Rakefile", "changelog.md"]

#### Code Highlighter
# 'pygments' is unsupported on GitHub Pages now.
highlighter: rouge

#### Permalink
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: pretty

#### Markdown Processors
# 'redcarpet' is unsupported on GitHub Pages now.
## 自改markdown代码块
markdown: kramdown
kramdown:
    input: GFM

#### Default Attributes
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

#### Pagination 每页显示多少个，这里我建议还是10个吧。也够用了
paginate: 15

#### Site
title : HealeJean的梦想博客
tagline: 一个高级软件开发工程师的成长之路 
assets: /assets
url:
baseurl:

#### Language
language: zh-CN    ## blog site languages: en, zh-CN, zh-TW, de

#### Menu
menu:
  主页: /
 # Tags: /tags
  技术: /categories
  归档: /archives
  生活日记: /daynote/日记
  留言板: /about
  友情链接: /friends


## you can create `tags` and `categories` folders (I had created them already).
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets:
- links
- person
# - category
- tag
- douban
- github-card
## provide seven widgets:github-card,category,tag,rss,archive,tagcloud,links,weibo,douban


#### RSS
rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.
apple_icon: img/jacman.jpg ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
author_img: img/author.jpg ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.
banner_img: #img/banner.jpg ## size:1920px*200px+. Banner Picture

#### index post is expanding or not
index:
  expand: false           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: Read More

close_aside: false  #close sidebar in post page if true
mathjax: true      #enable mathjax if true
share_to: true #enable share-to buttons if true

#### Author information
author:
  name: HealerJean      ## e.g. wuchong Author name
  intro_line1:  "欢迎来到  HealerJean 的梦想博客."    ## your introduction on the bottom of the page
  intro_line2:  "------您已走进一个高级软件开发工程师的成长之路"  ## the 2nd line
  weibo:     3889598250   ## e.g. wuchong1014 or 2176287895 for http://weibo.com/2176287895
  weibo_verifier:    ## a5131864 e.g. b3593ceb Your weibo-show widget verifier ,if you use weibo-show it is needed.
  tsina:      ## e.g.3889598250  2176287895  Your weibo ID,It will be used in share button.
  douban:   ## 166502514  ## e.g. wuchong1014 or your id for https://www.douban.com/people/wuchong1014
  zhihu:      ## e.g. jark  for http://www.zhihu.com/people/jark
  email:    mxzdhealer@gmail.com  ## e.g. imjark@gmail.com
  twitter:  mxzdhealer  ## e.g. jarkwu for https://twitter.com/jarkwu
  github: ##  HealerJean123  ## e.g. wuchong for https://github.com/wuchong
  facebook:   ## e.g. imjark for https://facebook.com/imjark
  linkedin:   ## e.g. wuchong1014 for https://www.linkedin.com/in/wuchong1014
  google_plus:    ## e.g. "111190881341800841449" for https://plus.google.com/u/0/111190881341800841449, the "" is needed!
  stackoverflow:  ## e.g. 3222790 for http://stackoverflow.com/users/3222790/jark
## if you set them, the corresponding  share button will show on the footer



#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
links:
  csdn: http://blog.csdn.net/u012954706
  博客园: http://www.cnblogs.com/HealerJean/
  微博: https://weibo.com/u/3889598250/
  简书: https://www.jianshu.com/u/54ba972e92a8
  知乎: https://www.zhihu.com/people/healerjean
#### Comment
duoshuo_shortname:    ## e.g. wuchong      your duoshuo short name.       website: http://duoshuo.com
disqus_shortname:     ## e.g. wuchong      your disqus short name.        website: http://disqus.com
hypercomments_id:     ## e.g. 91510        your hypercomments widget id.  website: http://hypercomments.com
yungentie_productkey: ## your netease yungentie product key.              website: https://gentie.163.com
## set only one of them
## duoshuo will be shutting down on June 1, 2017

#### Share button
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1889330 your jiathis ID.
  tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.

#### Analytics
google_analytics:
  enable: false
  id:        ## e.g. UA-46321946-2 your google analytics ID.
  site:      ## e.g. wuchong.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN
baidu_tongji:
  enable: false
  sitecode:  ## e.g. e6d1f421bbc9962127a50488f9ed37d1 your baidu tongji site code
cnzz_tongji:
  enable: false
  siteid:    ## e.g. 1253575964 your cnzz tongji site id

#### Miscellaneous
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true

#### Custom Search
google_cse:
  enable: false
  cx: 018294693190868310296:abnhpuysycw  ## e.g. 018294693190868310296:abnhpuysycw your Custom Search ID.
## https://www.google.com/cse/
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search
## title: search
## ---
#
#搜索框 
baidu_search:     ## http://zn.baidu.com/
  enable: false
  id:   ## e.g. "783281470518440642"  for your baidu search id
  site: http://zhannei.baidu.com/cse/search  ## your can change to your site instead of the default site
tinysou_search:     ## http://tinysou.com/
  enable: false
  id:  ## e.g. "4ac092ad8d749fdc6293" for your tiny search id
simple_jekyll_search:
  enable: true
  fulltext: false

gems:
 - jemoji

theme: jekyll-theme-cayman