/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hlj.struts.action;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.OutputStream;
import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.hlj.userseivice.UserService;

import co.hlj.domain.Users;

/** 
 * MyEclipse Struts
 * Creation date: 04-26-2015
 * 
 * XDoclet definition:
 * @struts.action
 */
public class DownfileAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String username = request.getParameter("username");
		System.out.println("传过来的参数为 username 为" +username); 
		UserService userService = new UserService();
		Users user = userService.getUser(username);
		System.out.println(user.getUsername());
 //开始下载了
		OutputStream oStream = null;
		FileInputStream fis = null;
		response.setContentType("text/html;charset=utf-8");
		
	//文件的名字有中文，进行处理
		
		try {
			response.setHeader("Content-Disposition", "attachment;filename="+java.net.URLEncoder.encode(user.getPhotoBefore(),"utf-8"));
		} catch (UnsupportedEncodingException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
						//打开文件，说明下web下载文件的原理 
						//1.获取要下载文件的全路径 
		String path1 = getServlet().getServletContext().getRealPath("/images/"+user.getPhotoNow());
		//这个时下载D盘的图片
		//File file = new File("D://a.jpg");
		//String path2 = file.getPath();
		//System.out.println(path2);
					System.out.println(path1);
					//下面就是打开这个文件(首先要读出了)	
					
					try {
						fis = new FileInputStream(path1); 
						oStream = response.getOutputStream();
						//	通过文件输入流写入文件     
									byte buffer[] = new byte[1024];    
									int len =0; //表示实际每次读取了多少个字节
									while((len=fis.read(buffer))>0){   
										oStream.write(buffer,0,len); 
									}  
					} catch (FileNotFoundException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					} catch (IOException e) { 
						// TODO Auto-generated catch block
						e.printStackTrace();
					}		
						
			    		try {
			    			fis.close();
							oStream.close();
						} catch (IOException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
			    	
		return null;
	}
}