/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hlj.struts.action;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import co.hlj.domain.Users;

import com.hlj.struts.form.UserForm;
import com.hlj.testUUID.TestUUID;
import com.hlj.userseivice.UserService;

/** 
 * MyEclipse Struts
 * Creation date: 04-25-2015
 * 
 * XDoclet definition:
 * @struts.action path="/register" name="userForm" scope="request"
 */
public class RegisterAction extends Action{
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
			
	String username = userForm.getUsername();
	FormFile myphoto = userForm.getMyphoto();
	String photoname = myphoto.getFileName();
		int photofilesize = myphoto.getFileSize();
	System.out.println(myphoto +" ：    "+ photofilesize); 
	InputStream is= null;
	OutputStream os = null;
	try
	 {
		
		//得到输入流
		is = myphoto.getInputStream();
		//获得输出流，取得文件的绝对路径
		String path  = this.getServlet().getServletContext().getRealPath("/images");
		System.out.println(path); 		 
		System.out.println(path); 		 
		System.out.println(path); 		 
		System.out.println(path); 		 
		String photonameNew = TestUUID.getUUIdName(photoname);
		os =new FileOutputStream(path+"\\"+photonameNew); 
		System.out.println(os+"\n\\n\n\n\\n\\\n\\"); 
		int len = 0;
		byte[] buffer =  new byte[1024]; 
		//这里的int代表实际读取了多少个字节
			
				while ((len=is.read(buffer))>0) {
					os.write(buffer, 0, len);					
				}
				UserService us = new UserService();
				Users users = new Users();
				users.setUsername(username);
				users.setPhotoBefore(photoname);
				users.setPhotoNow(photonameNew);
		if(us.addUser(users)==true){
			 
			return mapping.findForward("ok");
		}else{
			return mapping.findForward("err");

			
		}
	 	} catch (Exception e) {
		
	 		}finally{								
					try {
						
						is.close();
						if(os!=null||os.equals("")){
						os.close();	
						}
					//	return mapping.findForward("ok");
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
	 			}
	
	//通过formFile 我们可以获得什么信息
		return null;
	}
}