####################################
### DB
####################################
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/healerjean?characterEncoding=utf-8&useUnicode=true&autoReconnect=true&connectTimeout=3000&initialTimeout=1&socketTimeout=5000&useSSL=false&serverTimezone=CTT
      username: root
      password: 12345678
  redis:
    host: 127.0.0.1
    port: 6379