/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hlj.struts.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 04-25-2015
 * 
 * XDoclet definition:
 * @struts.form name="userForm"
 */
public class UserForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** username property */
	private String username;

	/** myphoto property */
	private FormFile myphoto;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the myphoto.
	 * @return String
	 */
	public FormFile getMyphoto() {
		return myphoto;
	}

	/** 
	 * Set the myphoto.
	 * @param myphoto The myphoto to set
	 */
	public void setMyphoto(FormFile myphoto) {
		this.myphoto = myphoto;
	}
}