server:
  port: 8888

####################################
### ????
####################################
spring:
  profiles:
    include: project-config


####################################
### DB
####################################
#durid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

####################################
### ??
####################################
logging:
  config: classpath:log4j2.xml


