/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hlj.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.constraints.Size;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.hlj.userseivice.UserService;
import com.hlj.util.SqlHelper1;

import co.hlj.domain.Users;

/** 
 * MyEclipse Struts
 * Creation date: 04-26-2015
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UserlistAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */ 
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
	//开始准配数据
		System.out.println("已经进入UserlistAction了 这个界面"); 
		UserService userService = new UserService();
		ArrayList<Users> users = userService.getUsers();
		System.out.println(users.size()); 
		request.setAttribute("users", users);
		return mapping.findForward("showuser"); 
	}
}