

###
POST http://localhost:8888/hlj/fileTask/save
{
  "userId": "healerjean",
  "taskType": "export",
  "businessType": "exportDemo",
  "businessData": "{\"phone\": \"1234567\"}",
  "taskStatus": "processing"
}
