/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hlj.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.hlj.domain.Users;
import com.hlj.service.UserService;
import com.hlj.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-26-2015
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="userForm" parameter="flag" scope="request"
 */
public class LoginAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward loginok(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		System.out.println("###############################"+userForm.getName());
		System.out.println("####################################"+userForm.getPassword());
		 Users user = new Users(); 
		 user.setName(userForm.getName());
		 user.setPassword(userForm.getPassword());
		 System.out.println(user.getName()+"这是名字");
		 System.out.println(user.getPassword()+"这是密码");
 
		 UserService userService = new UserService();
		 
		 if (userService.checkUser(user)) {   
			 request.getSession().setAttribute("user", user);
			 System.out.println(user.getName()+"这是名字");
				return mapping.findForward("loginok");
  
		}else {
			return mapping.findForward("loginerr");
		}
		
		
		
	}
}