/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hlj.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.hlj.struts.form.MassageForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-26-2015
 * 
 * XDoclet definition:
 * @struts.action path="/message" name="massageForm" parameter="flag" scope="request"
 */
public class MessageAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward gopublish(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		MassageForm massageForm = (MassageForm) form;// TODO Auto-generated method stub
		System.out.println("这里就是来了"); 
		
		return mapping.findForward("gopublish"); 
	}
}