#POST http://localhost.admin:8888/api/user/login
#Accept: */*
#Cache-Control: no-cache
#Content-Type: application/json
#
#{"username":"healerjean","password":"admin"}

###




#GET http://localhost:8888/api/user/current
#Cookie: scf-manager_SID=489e370c329b4a15bf847fb8d542fae4

//Cookie: scf-manager_SID=458d40daf84944039045d4aaa8de8a25



# 执行任务
#GET http://localhost:8888/api/flow/startJob
#Cookie: scf-manager_SID=e343895c9e1e4b9fb9fe5fb75390cf61



#GET http://localhost:8888/api/flow/continueJob?instanceNo=068e295679f54f9d9bb710f143878ae1&nextFlow=true
#Cookie: scf-manager_SID=e343895c9e1e4b9fb9fe5fb75390cf61


#GET http://localhost:8888/api/flow/auditFlowStartJob
#Cookie: scf-manager_SID=980605da04154360b980a2dd43461091

###

#继续流程
#GET http://localhost:8888/api/flow/continueAuditFlowJob?instanceNo=4f3e2d4d89054a29ad0c2ad5bea56f5f&nextFlow=true
#Cookie: scf-manager_SID=980605da04154360b980a2dd43461091



#GET http://localhost:8888/api/flow/audit?auditRecordId=4
#Cookie: scf-manager_SID=980605da04154360b980a2dd43461091

###

POST http://localhost:8888/api/flow/audit
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Cookie: scf-manager_SID=980605da04154360b980a2dd43461091

{"auditRecordId":4,"auditResult":true}

###








