#POST http://localhost:8888/api/user/login
#Accept: */*
#Cache-Control: no-cache
#Content-Type: application/json
#
#{"username":"healerjean","password":"admin"}

###


#GET http://localhost:8888/api/user/current
#Cookie: scf-manager_SID=489e370c329b4a15bf847fb8d542fae4



# 执行任务
#GET http://localhost:8888/api/flow/startJob
#Cookie: scf-manager_SID=e343895c9e1e4b9fb9fe5fb75390cf61



#GET http://localhost:8888/api/flow/continueJob?instanceNo=068e295679f54f9d9bb710f143878ae1&nextFlow=true
#Cookie: scf-manager_SID=e343895c9e1e4b9fb9fe5fb75390cf61




#GET http://localhost:8888/api/flow/auditFlowStartJob
#Cookie: scf-manager_SID=838c87f1818249a7a45459ad06eabf8e



#继续流程
#GET http://localhost:8888/api/flow/continueAuditFlowJob?instanceNo=7f4744bd0e264d36b67a3538c9f279a3&nextFlow=true
#Cookie: scf-manager_SID=838c87f1818249a7a45459ad06eabf8e

POST http://localhost:8888/api/flow/audit
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Cookie: scf-manager_SID=838c87f1818249a7a45459ad06eabf8e

{"auditRecordId":12,"auditResult":true}

###












