/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hlj.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.hlj.domain.Message;
import com.hlj.domain.Users;
import com.hlj.service.inter.MessageServiceInter;
import com.hlj.struts.form.UserForm;
import com.sina.service.imp.MessageServiceImp;

/** 
 * MyEclipse Struts
 * Creation date: 04-30-2015
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class GoMessageUiAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
	//取出收到的信息
		
		MessageServiceInter messageServiceInter = new MessageServiceImp(); 
		Users user = (Users)request.getSession().getAttribute("userinfo");
		 
		List<Message> messages = messageServiceInter.showMessages();
		request.setAttribute("message", messages);  
		//获取需要显示的留言信息，完成跳转
		return mapping.findForward("goMessageUi"); 
	}
}