--- 
name: OSCache 2.4.1 Binary
platform_id: all
platform_version: all
distribution_file_uuid_string: openlogic-oscache-2.4.1-all-bin-1
platform_vendor: all
description: OSCache 2.4.1 Binary
platform_arch: all
distribution_file_uuid: 47d71ebfe0d1bf4ee5c60bdbbdfaac42080925d9823f820fa4385618ba42d825
distribution_version: 1
distribution_flavor: ""
distribution_raw_file: oscache-2.4.1-full.zip
package_version: 2.4.1
package_id: oscache
release_date: "2008-03-14"
distribution_notes: ""
distribution_type: bin
