/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hlj.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.hlj.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-25-2015
 * 
 * XDoclet definition:
 * @struts.action path="/loginAndDis" name="userForm" scope="request"
 */
public class LoginAndDisAction extends DispatchAction {
	
/*使用分派dispathAction
 * 要自己重新命名函数*/
	
	public ActionForward loginuser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		if(userForm.getPassword().equals("123")){
			
			return mapping.findForward("loginok");
		}
		return null;
	}
	
//用于响应注销请求
	
	public ActionForward userloginout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		return null;
	}
}


